"""Configuration package for Red Teaming system."""

from .settings import (
    AZURE_OPENAI_ENDPOINT,
    AZURE_OPENAI_API_KEY,
    AZURE_OPENAI_DEPLOYMENT,
    AZURE_OPENAI_API_VERSION,
    WEBSOCKET_URL,
    WEBSOCKET_TIMEOUT,
    WEBSOCKET_MAX_RETRIES,
    TOTAL_RUNS,
    TURNS_PER_RUN,
    CONTEXT_WINDOW_SIZE,
    RISK_CATEGORIES,
    DUCKDB_PATH,
    ARCHITECTURE_FILE,
    validate_config
)

__all__ = [
    "AZURE_OPENAI_ENDPOINT",
    "AZURE_OPENAI_API_KEY",
    "AZURE_OPENAI_DEPLOYMENT",
    "AZURE_OPENAI_API_VERSION",
    "WEBSOCKET_URL",
    "WEBSOCKET_TIMEOUT",
    "WEBSOCKET_MAX_RETRIES",
    "TOTAL_RUNS",
    "TURNS_PER_RUN",
    "CONTEXT_WINDOW_SIZE",
    "RISK_CATEGORIES",
    "DUCKDB_PATH",
    "ARCHITECTURE_FILE",
    "validate_config"
]
