name: MLP Feature Request
description: Propose a feature for the Minimum Lovable Product
title: "[MLP]: "
labels: ["mlp", "enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## MLP Feature Request
        Use this template to propose features for the Chatbot Security Testing Agent MLP.
        
  - type: dropdown
    id: feature-category
    attributes:
      label: Feature Category
      description: Which core feature does this relate to?
      options:
        - PyRIT Integration Engine
        - Multi-Chatbot Connector
        - Vulnerability Detection Dashboard
        - Attack Scenario Builder
        - Comprehensive Reporting
        - Other
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Describe the feature you'd like to see
      placeholder: A clear and concise description of the feature...
    validations:
      required: true
      
  - type: dropdown
    id: use-case
    attributes:
      label: Primary Use Case
      description: Which use case does this feature support?
      options:
        - Automated Vulnerability Scanning
        - Red Team Attack Simulation
        - Prompt Injection Testing
        - Compliance Validation
        - Continuous Security Monitoring
        - Other
    validations:
      required: true
      
  - type: textarea
    id: user-story
    attributes:
      label: User Story
      description: Describe the user story for this feature
      placeholder: "As a [user type], I want [feature] so that [benefit]..."
    validations:
      required: true
      
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What are the acceptance criteria for this feature?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: true
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: What priority should this feature have?
      options:
        - P0 - Critical
        - P1 - High
        - P2 - Medium
        - P3 - Low
    validations:
      required: true
      
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or references
      placeholder: Links, images, or additional details...
